name: Notify Contributors

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Contributors
        id: contributors
        run: |
            CONTRIBUTORS=$(curl -s -H "Authorization: token ${{ secrets.CATEGORY_ID }}" \
      "https://api.github.com/repos/${{ github.repository }}/contributors" | jq -r '.[].login')
    
    # Format mentions correctly (space-separated instead of newline)
    CONTRIBUTORS=$(echo "$CONTRIBUTORS" | awk '{printf "@%s ", $0}')
    
    echo "contributors=$CONTRIBUTORS" >> $GITHUB_ENV

      - name: Create Discussion Post
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.CATEGORY_ID }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/discussions \
            -d '{
              "title": "Announcement",
              "body": "Hey '"$contributors"'! this is an important announcement.",
              "category_id": "YOUR_CATEGORY_ID"
            }'
