name: Notify All Collaborators When Label "everyone" is Added

on:
  issues:
    types: [labeled]  # Se activa cuando se añade una etiqueta a un issue.

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is "everyone"
        if: contains(github.event.label.name, 'everyone')
        run: echo "Label 'everyone' detected. Sending mail notification."

      - name: Send Email via Gmail SMTP
        if: contains(github.event.label.name, 'everyone')
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "🤖 New issue: ${{ github.event.issue.title }}"
          body: |
            ‼️ There's a new issue labelled 'everyone'.

            Title: ${{ github.event.issue.title }}
            Description: ${{ github.event.issue.body }}
            See more: ${{ github.event.issue.html_url }}

          to: ${{ secrets.EMAIL_RECIPIENTS }}
          from: "🤖 Marbits Bot <marbits.icm@gmail.com>"
