name: Notify All Collaborators When Label "everyone" is Added

on:
  issues:
    types: [labeled]  # Se activa cuando se a침ade una etiqueta a un issue.

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is "everyone"
        if: contains(github.event.label.name, 'everyone')
        run: echo "Etiqueta 'everyone' detectada. Enviando notificaci칩n por email."

      - name: Send Email via Gmail SMTP
        if: contains(github.event.label.name, 'everyone')
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Nuevo Issue: ${{ github.event.issue.title }}"
          body: |
            游댒 Se ha etiquetado un nuevo issue con 'TODOS'.

            T칤tulo: ${{ github.event.issue.title }}
            Descripci칩n: ${{ github.event.issue.body }}
            Ver m치s: ${{ github.event.issue.html_url }}

          to: "pablo.sanchez@gmail.com, pablosanchez@gmail.com"
          from: "GitHub Bot <pablo.sanchez@gmail.com>"
